SELECT TOP (1000) [StrategyGroupTitle]
      ,[StrategyGroupLevel]
      ,[StrategyId]
      ,[StrategyPosition]
      ,[StrategyTitle]
      ,[StrategyTitleShort]
      ,[StrategyDescription]
      ,[StrategyResponsibleOfficerName]
      ,[StrategyGroupSystemPeriod]
      ,[ActionTitle]
      ,[ActionDescription]
      ,[ActionPosition]
      ,[ActionResponsibleOfficer]
      ,[ActionStartDate]
      ,[ActionRevisedStartDate]
      ,[ActionEndDate]
      ,[ActionRevisedEndDate]
      ,[ActionProgressUpdateDate]
      ,[ActionCompletionDate]
      ,[ActionPercentComplete]
      ,[ActionStatus]
      ,[StratActionServiceProfileName]
      ,[StratActionServiceProfileId]
      ,[ActionProgressComment]
      ,[ActionId]
  FROM [KCC_DataWarehouse].[dbo].[CORPREPORT_Actions] where StrategyGroupSystemPeriod like '%2018%'


  SELECT [KPIACTUALID]
      ,[KPIID]
      ,[REPORTINGPERIODID]
      ,[STRATEGICGROUPINGID]
      ,[STRATEGYID]
      ,[SERVICEPROFILEID]
      ,[BUSINESSUNITID]
      ,[ACTIONID]
      ,[DIRECTORATEID]
      ,[TARGET]
      ,[ACTUAL]
      ,[VARIANCE]
      ,[ACTIVE]
      ,[LASTCHANGE]
      ,[MODIFEDBY]
      ,[KPINODEID]
      ,[COMMENT]
      ,[PROJECTCOMMENTS]
      ,[BENCHMARK]
      ,[FORECAST]
      ,[BENCHMARK1]
      ,[BENCHMARK2]
      ,[BENCHMARK3]
      ,[BENCHMARK4]
      ,[HierarchyNodeId]
  FROM [InterplanV4].[dbo].[KPIACTUAL] where LASTCHANGE like '%2019%'